name: "Auto Changelog"

on:
  issue_comment:
    types: [created]

jobs:
  auto-changelog:
    env: 
      COMMENT_BODY: ${{ github.event.comment.body }}
    if: ${{ (contains(github.event.comment.body, '+changelog') || contains(github.event.comment.body, '-changelog')) && github.event.comment.user.login == github.event.issue.user.login }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - run: |
          echo '${{ github.head_ref }}'
          echo '${{ github.ref_name }}'