name: "[Automatic] PR Changelog"

on:
  issue_comment:
    types: [created]

jobs:
  auto-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Script Execution
        uses: actions/github-script@v7
        with:
          script: | 
            console.log(JSON.stringify(context));