name: Auto PR Description

on:
  pull_request:
    types: [opened, synchronize]

env:
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}

jobs:
  explain-diff:
    runs-on: ubuntu-latest
    env:
      DIFF_URL: ${{ github.event.pull_request.diff_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get Github Diff
        id: myRequest
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ env.DIFF_URL }}

      - name: Print Diff
        run: |
          echo ${{ fromJson(steps.myRequest.outputs.response).data }}
    