name: "[Automatic] PR Changelog"

on:
  issue_comment:
    types: [created]

jobs:
  auto-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Script Execution
        uses: actions/github-script@v7
        with:
          script: | 
            console.log('${{ github.event_name }}');
            console.log('${{ toJson(github.issue_comment) }}');
            console.log('${{ toJson(github.event) }}');