name: Auto PR Description

on:
  pull_request:
    types: [opened, synchronize]

env:
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}

jobs:
  explain-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get Diff
        id: get-diff
        run: |
          echo "GIT_DIFF=$(git diff origin/$BASE_REF...$HEAD_REF)\n" >> $GITHUB_OUTPUT

      - name: Print Diff
        run: echo ${{ steps.get-diff.outputs.GIT_DIFF}}
    