name: Auto PR Description

on:
  pull_request:
    types: [opened, synchronize]

env:
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}

jobs:
  explain-diff:
    runs-on: ubuntu-latest
    env:
      DIFF_URL: ${{ github.event.pull_request.diff_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get Github Diff
        id: myRequest
        run: |
          curl -s "$DIFF_URL" -o diff.txt
          echo "GIT_DIFF<<EOF" >> $GITHUB_OUTPUT
          cat diff.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Print Diff
        run: |
          echo ${{ steps.myRequest.outputs.GIT_DIFF }}
    