name: Git Mergeable Merge-Into

on:
  workflow_call:
    inputs:
      mergeable-id:
        description: Mergeable branch @ repo short url -> Destination branch.
        required: true
        default: feature/mergeable/...@RedEyeMods/.github->main
        type: string
      target-repo:
        type: string
        description: The repository to merge into.
        default: "~"
        required: false
    secrets:
      GPG_PRIVATE_KEY:
        description: 'Private GPG key for commit signing'
        required: true
      GPG_SIGNING_PASSPHRASE:
        description: 'The passphrase for the GPG_PRIVATE_KEY'
        required: true
      PR_PAT:
        description: 'The personal access token for the PR user'
        required: true

jobs:
  translate-input:
    name: Translate Input
    runs-on: ubuntu-latest
    outputs:
      source-branch: ${{ steps.translate.outputs.source-branch }}
      source-repo: ${{ steps.translate.outputs.source-repo }}
      target-branch: ${{ steps.translate.outputs.target-branch }}
    steps:
      - name: Translate branch and repo input
        id: translate
        uses: actions/github-script@v7
        with:
          script: |
            const input = "${{ inputs.mergeable-id }}";
            const match = input.match(/([\w-\/]+)@([^/]+)\/(.+)->(.+)/);
            if (match) {
              const branchName = match[1];
              const repoShortUrl = `${match[2]}/${match[3]}`;
              const intoBranch = match[4];
              core.setOutput('source-branch', branchName);
              core.setOutput('source-repo', repoShortUrl);
              core.setOutput('target-branch', intoBranch);
            } else {
              throw new Error('Invalid input format. Expected format: branch/name@owner/repo');
            }
   
  merge-and-pr:
    name: Merge Changes
    needs: translate-input
    runs-on: ubuntu-latest
    steps:       
      - name: Determine checkout target
        run: |
          if [ "${{ inputs.target-repo }}" == "~" ]; then
            echo "Target repo is ${{ github.repository }}."
            echo "target-repo=${{ github.repository }}" >> $GITHUB_ENV
          else
            echo "Target repo is ${{ inputs.target-repo }}"
            echo "target-repo=${{ inputs.target-repo }}" >> $GITHUB_ENV
          fi
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.translate-inputs.outputs.target-branch }}
          repository: ${{ env.target-repo }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          
      - name: Add New Remote
        run: |
          git remote add auto-merge https://github.com/${{ needs.translate-inputs.outputs.source-repo }}.git
          git fetch auto-merge ${{ needs.translate-inputs.outputs.source-branch }}

      - name: Simulate merge
        id: simulate-merge
        run: |
          git merge --no-commit --no-ff --allow-unrelated-histories auto-merge/${{ needs.translate-inputs.outputs.source-branch }} || echo "Merge conflicts detected"
          if [ "$(git diff --name-only HEAD)" != "" ]; then
            echo "Merge would result in changes."
            echo "merge_needed=true" >> $GITHUB_ENV
          else
            echo "Merge would not result in any changes."
            echo "merge_needed=false" >> $GITHUB_ENV
          fi
          git merge --abort
          
      - name: Merge Results
        if: env.merge_needed == 'true'
        id: merge
        run: |
          git merge -X theirs --allow-unrelated-histories auto-merge/${{ needs.translate-inputs.outputs.source-branch }}

      - name: Ensure .gitmergeables entry
        if: env.merge_needed == 'true'
        id: ensure-mergeables
        uses: actions/github-script@v7
        with:
          script: |
            const entry = '${{ inputs.mergeable-id }}';
            const filePath = '.gitmergeables';
            const fs = require('fs');
            const path = require('path');

            // Check if the file exists and read its content if it does
            let fileContent = '';
            if (fs.existsSync(filePath)) {
              fileContent = fs.readFileSync(filePath, 'utf8');
            }

            // Ensure the entry exists
            if (!fileContent.includes(entry)) {
              // Add the entry to the file content
              fileContent += `${entry}\n`;
              
              // Write the updated content back to the file
              fs.writeFileSync(filePath, fileContent, 'utf8');

              // Stage the changes, commit, and push
              const execSync = require('child_process').execSync;
              execSync('git add ' + filePath);
              execSync(`git commit -m "Add .gitmergeables entry: ${entry}"`);
            } else {
              console.log('Entry already exists in .gitmergeables');
            }
          result-encoding: json

      - name: Create Pull Request
        if: steps.merge.outcome == 'success'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PR_PAT }}
          title: "Update ${{ needs.translate-inputs.outputs.source-repo }}/${{ needs.translate-inputs.outputs.source-branch }}"
          body: ""
          branch: chore/mergeables/update/${{ needs.translate-inputs.outputs.source-branch }}
          author: "RedEyeMods <redeyemodding@gmail.com>"
