name: Update Mergeable

on: 
  workflow_dispatch:
    inputs:
      source-repo:
        type: string
        description: Repository which contains the mergeable workflow branch.
        default: RedEyeMods/.github
        required: true
      source-branch:
        type: string
        description: Branch on the repository to merge from.
        required: true
      target-repo:
        type: string
        description: The repository to merge into.
        default: "~"
        required: false
      target-branch:
        type: string
        description: The branch to merge into.
        default: main
        required: false
      force-merge:
        type: boolean
        description: Whether we force with allow-unrelated-histories.
        default: false
        required: false
        

jobs:
  install-desired:
    name: Install Mergeable
    uses: RedEyeMods/.github/.github/workflows/gh-mergeable-install.yml@feature/reusable-workflows
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
      PR_PAT: ${{ secrets.ORG_PAT }}
    with:
      mergeable-id: ${{ inputs.source-branch }}@${{ inputs.source-repo }}->${{ inputs.target-branch }}
      target-repo: ${{ inputs.target-repo }}
